# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18f58e1f5627cc756e74bb333699b17605b7a07a1831e84072efe800606db71b89d63369b8a251bae3b8b81086479cd9222024a58e51a2a7a299a66e129a8450

test:
  secret_key_base: 4d1712f04dd3439bf84616f32c54ec77ec8370ba3603839037ef776f4d32bf7d6c891462f9ac1b2875ac1ffb4ab28ba14eb4dbda5e082207c62d053cb3f0485f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
